# -*- coding: utf-8 -*-
"""Retail_Customer_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKCEUJWTWoDlsGyjIEkKevk7MUAEwkwm

# 🛒 Phân Tích Dữ Liệu & Dự Đoán Khách Hàng Bán Lẻ/E-commerce
### Retail & E-commerce Customer Analytics Project

**Mục tiêu dự án:** Xây dựng pipeline phân tích dữ liệu (Data Analytics) hoàn chỉnh cho doanh nghiệp bán lẻ/e-commerce, mô phỏng các kỹ thuật mà **doanh nghiệp Việt Nam** (Tiki, Shopee, Sendo, các chuỗi retail...) thường triển khai trong bộ phận Data/BI.

**Các kỹ thuật sử dụng trong notebook:**

| Nhóm | Kỹ thuật | Ứng dụng thực tế |
|---|---|---|
| EDA | Trực quan hóa xu hướng doanh thu, sản phẩm, thị trường | Báo cáo kinh doanh (BI report) |
| Feature Engineering | RFM (Recency – Frequency – Monetary) | Phân loại giá trị khách hàng |
| Unsupervised ML | KMeans Clustering + PCA | Phân khúc khách hàng (Customer Segmentation) |
| Time-based Analysis | Cohort Analysis (Retention Heatmap) | Đo lường khả năng giữ chân khách hàng |
| Association Rules | Market Basket Analysis (Apriori) | Gợi ý sản phẩm, cross-sell/up-sell |
| Supervised ML - Classification | Logistic Regression, Random Forest, Gradient Boosting, XGBoost | Dự đoán khách hàng rời bỏ (Churn Prediction) |
| Supervised ML - Regression | Linear Regression, Random Forest, Gradient Boosting, XGBoost | Dự đoán giá trị khách hàng (CLV) |
| Model Storage | joblib, CSV, Parquet | Lưu trữ mô hình & kết quả để triển khai |
| Dashboard | Plotly + ipywidgets tương tác | Dashboard nội bộ cho stakeholder |

**Dataset:** [Online Retail Dataset – UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/352/online+retail) — dữ liệu giao dịch thực tế của một doanh nghiệp bán lẻ online tại Anh (12/2010 – 12/2011), gồm ~540,000 giao dịch. Đây là bộ dữ liệu retail/e-commerce transactional kinh điển, được dùng rộng rãi trong giới Data Analyst/Scientist để luyện tập RFM, Customer Segmentation, Market Basket Analysis.

> 💡 **Chạy trên Google Colab:** Chỉ cần chạy tuần tự từ trên xuống dưới (Runtime → Run all). Notebook sẽ tự tải dữ liệu, tự cài thư viện cần thiết.

## 1. Cài đặt thư viện
"""

# Cài các thư viện chưa có sẵn trên Colab
!pip install -q mlxtend xgboost openpyxl ipywidgets
print(" Đã cài đặt xong thư viện.")

import warnings
warnings.filterwarnings("ignore")

import os
import io
import requests
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import (RandomForestClassifier, RandomForestRegressor,
                               GradientBoostingClassifier, GradientBoostingRegressor)
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                              roc_auc_score, roc_curve, confusion_matrix,
                              mean_absolute_error, mean_squared_error, r2_score)
import xgboost as xgb

from mlxtend.frequent_patterns import apriori, association_rules

import joblib
import ipywidgets as widgets
from IPython.display import display

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 5)

# Tạo các thư mục lưu trữ output theo chuẩn 1 project DA thực tế
os.makedirs("outputs", exist_ok=True)
os.makedirs("outputs/models", exist_ok=True)
os.makedirs("outputs/data", exist_ok=True)
os.makedirs("outputs/figures", exist_ok=True)

print("Đã import xong toàn bộ thư viện.")

"""## 2. Tải dữ liệu

Notebook tự động tải bộ dữ liệu **Online Retail** trực tiếp từ UCI Machine Learning Repository — không cần upload file tay, không cần API key.

Nếu vì lý do nào đó (mạng, server UCI bảo trì...) việc tải thất bại, notebook sẽ **tự sinh một bộ dữ liệu mô phỏng cùng cấu trúc cột** để toàn bộ pipeline phía dưới vẫn chạy được bình thường — bạn sẽ thấy cảnh báo rõ ràng nếu điều này xảy ra.

"""

DATA_URL = "https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx"
LOCAL_PATH = "outputs/data/online_retail_raw.xlsx"

def download_real_dataset(url, local_path):
    """Tải dataset Online Retail thật từ UCI. Trả về DataFrame hoặc None nếu lỗi."""
    try:
        print(f" Đang tải dữ liệu từ: {url}")
        headers = {"User-Agent": "Mozilla/5.0 (compatible; Colab-Notebook/1.0)"}
        r = requests.get(url, timeout=60, headers=headers)
        r.raise_for_status()
        with open(local_path, "wb") as f:
            f.write(r.content)
        df_raw = pd.read_excel(local_path, engine="openpyxl")
        print(f"Tải thành công! Shape: {df_raw.shape}")
        return df_raw
    except Exception as e:
        print(f" Không tải được dữ liệu thật ({e}).")
        return None


def generate_synthetic_dataset(n_rows=25000, seed=42):
    """
    Sinh dữ liệu retail mô phỏng ĐÚNG cấu trúc cột của Online Retail dataset,
    dùng khi không thể kết nối tới UCI. Giúp notebook luôn chạy được (fail-safe).
    """
    rng = np.random.default_rng(seed)
    n_customers, n_products = 800, 200
    customers = [f"{13000+i}" for i in range(n_customers)]
    countries = ["United Kingdom","France","Germany","Spain","Netherlands",
                 "EIRE","Belgium","Portugal","Australia","Norway"]
    country_w = [0.60,0.08,0.08,0.05,0.05,0.04,0.03,0.03,0.02,0.02]
    stock_codes = [f"{10000+i}" for i in range(n_products)]
    descriptions = [f"PRODUCT {i}" for i in range(n_products)]

    period_start = pd.Timestamp("2019-12-01")
    period_end = pd.Timestamp("2020-12-09")
    total_hours = int((period_end - period_start) / pd.Timedelta(hours=1))

    # Mỗi khách hàng có 1 vòng đời: ngày bắt đầu mua và ngày ngừng mua (mô phỏng churn thật,
    # thay vì hoạt động đều suốt cả năm - giúp các bước Cohort và Churn phía sau có ý nghĩa
    cust_start = rng.integers(0, int(total_hours * 0.6), n_customers)
    is_churner = rng.random(n_customers) < 0.35
    cust_end = np.where(
        is_churner,
        cust_start + rng.integers(24, int(total_hours * 0.5), n_customers),
        np.full(n_customers, total_hours),
    )
    cust_end = np.minimum(cust_end, total_hours)

    idx_cust = rng.integers(0, n_customers, n_rows)
    idx_prod = rng.integers(0, n_products, n_rows)

    starts = cust_start[idx_cust]
    ends = np.maximum(cust_end[idx_cust], starts + 1)
    hour_offsets = (rng.random(n_rows) * (ends - starts)).astype(int)
    hour_idx = np.clip(starts + hour_offsets, 0, total_hours - 1)
    invoice_dates = period_start + pd.to_timedelta(hour_idx, unit="h")

    df_syn = pd.DataFrame({
        "InvoiceNo": [f"5{rng.integers(10000,99999)}" for _ in range(n_rows)],
        "StockCode": np.array(stock_codes)[idx_prod],
        "Description": np.array(descriptions)[idx_prod],
        "Quantity": rng.integers(1, 30, n_rows),
        "InvoiceDate": invoice_dates,
        "UnitPrice": np.round(rng.uniform(0.5, 50, n_rows), 2),
        "CustomerID": np.array(customers)[idx_cust],
        "Country": rng.choice(countries, n_rows, p=country_w),
    })

    # Mô phỏng đơn hủy (Invoice bắt đầu bằng 'C') và giá trị thiếu, giống dữ liệu thật
    cancel_mask = rng.random(n_rows) < 0.02
    df_syn.loc[cancel_mask, "InvoiceNo"] = "C" + df_syn.loc[cancel_mask, "InvoiceNo"]
    df_syn.loc[cancel_mask, "Quantity"] = -df_syn.loc[cancel_mask, "Quantity"]

    missing_mask = rng.random(n_rows) < 0.03
    df_syn.loc[missing_mask, "CustomerID"] = np.nan

    return df_syn


df_raw = download_real_dataset(DATA_URL, LOCAL_PATH)

if df_raw is None:
    print(" Chuyển sang dữ liệu mô phỏng (synthetic fallback) để pipeline vẫn hoạt động đầy đủ.")
    df_raw = generate_synthetic_dataset()
    USING_SYNTHETIC = True
else:
    USING_SYNTHETIC = False

print(f"\nĐang sử dụng: {'DỮ LIỆU MÔ PHỎNG (fallback)' if USING_SYNTHETIC else 'DỮ LIỆU THẬT (UCI Online Retail)'}")
df_raw.head()

"""## 3. Khám phá dữ liệu ban đầu (Data Profiling)"""

print("Kích thước dữ liệu:", df_raw.shape)
print("\nKiểu dữ liệu:")
print(df_raw.dtypes)
print("\nSố giá trị thiếu theo cột:")
print(df_raw.isna().sum())
print("\nThống kê mô tả:")
df_raw.describe(include="all").T

"""## 4. Làm sạch dữ liệu (Data Cleaning)

Các bước làm sạch chuẩn cho dữ liệu giao dịch bán lẻ:
- Loại bỏ giao dịch không có `CustomerID` (không thể gắn với 1 khách hàng cụ thể)
- Loại bỏ đơn hàng bị **hủy** (InvoiceNo bắt đầu bằng `C`)
- Loại bỏ `Quantity` hoặc `UnitPrice` ≤ 0 (dữ liệu lỗi/trả hàng)
- Tạo cột `Revenue = Quantity × UnitPrice`

"""

df = df_raw.copy()

df = df.dropna(subset=["CustomerID"])
df["CustomerID"] = df["CustomerID"].astype(str).str.replace(".0", "", regex=False)
df["InvoiceNo"] = df["InvoiceNo"].astype(str)

before = len(df)
df = df[~df["InvoiceNo"].str.startswith("C")]
df = df[(df["Quantity"] > 0) & (df["UnitPrice"] > 0)]
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

print(f"Số dòng trước khi làm sạch: {before:,}")
print(f"Số dòng sau khi làm sạch:   {len(df):,}  ({len(df)/before:.1%} giữ lại)")
print(f"Khoảng thời gian dữ liệu: {df['InvoiceDate'].min().date()} → {df['InvoiceDate'].max().date()}")
print(f"Số khách hàng duy nhất: {df['CustomerID'].nunique():,}")
print(f"Số quốc gia: {df['Country'].nunique()}")

df.to_csv("outputs/data/clean_transactions.csv", index=False)
df.head()

"""## 5. Phân tích khám phá dữ liệu (EDA) & Trực quan hóa

### 5.1. Xu hướng doanh thu theo thời gian
"""

df["InvoiceMonth"] = df["InvoiceDate"].dt.to_period("M").astype(str)
monthly_rev = df.groupby("InvoiceMonth")["Revenue"].sum().reset_index()

fig = px.line(monthly_rev, x="InvoiceMonth", y="Revenue", markers=True,
              title="Doanh thu theo tháng (Monthly Revenue Trend)")
fig.update_layout(xaxis_title="Tháng", yaxis_title="Doanh thu (£)")
fig.write_html("outputs/figures/monthly_revenue.html")
fig.show()

"""### 5.2. Top sản phẩm & top quốc gia"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

top_products = df.groupby("Description")["Revenue"].sum().sort_values(ascending=False).head(10)
sns.barplot(x=top_products.values, y=top_products.index, ax=axes[0], palette="viridis")
axes[0].set_title("Top 10 sản phẩm theo doanh thu")
axes[0].set_xlabel("Doanh thu (£)")

top_countries = df.groupby("Country")["Revenue"].sum().sort_values(ascending=False).head(10)
sns.barplot(x=top_countries.values, y=top_countries.index, ax=axes[1], palette="magma")
axes[1].set_title("Top 10 quốc gia theo doanh thu")
axes[1].set_xlabel("Doanh thu (£)")

plt.tight_layout()
plt.savefig("outputs/figures/top_products_countries.png", dpi=150)
plt.show()

"""### 5.3. Hành vi mua hàng theo thời gian (giờ trong ngày / ngày trong tuần)"""

df["Hour"] = df["InvoiceDate"].dt.hour
df["DayOfWeek"] = df["InvoiceDate"].dt.day_name()

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

hourly = df.groupby("Hour")["Revenue"].sum()
sns.barplot(x=hourly.index, y=hourly.values, ax=axes[0], color="steelblue")
axes[0].set_title("Doanh thu theo giờ trong ngày")
axes[0].set_xlabel("Giờ"); axes[0].set_ylabel("Doanh thu (£)")

day_order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
daily = df.groupby("DayOfWeek")["Revenue"].sum().reindex(day_order)
sns.barplot(x=daily.index, y=daily.values, ax=axes[1], color="coral")
axes[1].set_title("Doanh thu theo ngày trong tuần")
axes[1].tick_params(axis="x", rotation=30)

plt.tight_layout()
plt.savefig("outputs/figures/time_patterns.png", dpi=150)
plt.show()

"""### 5.4. Phân phối giá trị đơn hàng"""

order_value = df.groupby("InvoiceNo")["Revenue"].sum()

fig = px.histogram(order_value[order_value < order_value.quantile(0.95)],
                    nbins=50, title="Phân phối giá trị đơn hàng (đã loại outlier top 5%)")
fig.update_layout(xaxis_title="Giá trị đơn hàng (£)", yaxis_title="Số lượng đơn")
fig.write_html("outputs/figures/order_value_dist.html")
fig.show()

"""## 6. Feature Engineering: Phân tích RFM

**RFM** là kỹ thuật kinh điển và được sử dụng rộng rãi nhất trong ngành retail/e-commerce (kể cả tại các doanh nghiệp Việt Nam) để định lượng giá trị khách hàng:

- **Recency (R):** Số ngày kể từ lần mua gần nhất → khách hàng còn "active" không
- **Frequency (F):** Số lần mua hàng → mức độ trung thành
- **Monetary (M):** Tổng chi tiêu → giá trị mang lại

Từ 3 chỉ số này, ta chấm điểm (1-4) theo quartile rồi gộp thành **RFM Score** để phân loại khách hàng thành các nhóm có ý nghĩa kinh doanh.

"""

snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

rfm = df.groupby("CustomerID").agg(
    Recency=("InvoiceDate", lambda x: (snapshot_date - x.max()).days),
    Frequency=("InvoiceNo", "nunique"),
    Monetary=("Revenue", "sum"),
).reset_index()

rfm["R_score"] = pd.qcut(rfm["Recency"], 4, labels=[4,3,2,1], duplicates="drop").astype(int)
rfm["F_score"] = pd.qcut(rfm["Frequency"].rank(method="first"), 4, labels=[1,2,3,4]).astype(int)
rfm["M_score"] = pd.qcut(rfm["Monetary"], 4, labels=[1,2,3,4], duplicates="drop").astype(int)
rfm["RFM_Score"] = rfm["R_score"] + rfm["F_score"] + rfm["M_score"]

def rfm_segment(score):
    if score >= 10: return "Champions"
    elif score >= 8: return "Loyal Customers"
    elif score >= 6: return "Potential Loyalist"
    elif score >= 4: return "At Risk"
    else: return "Lost / Hibernating"

rfm["Segment"] = rfm["RFM_Score"].apply(rfm_segment)

print(rfm["Segment"].value_counts())
rfm.head()

fig = px.pie(rfm, names="Segment", title="Phân bổ khách hàng theo phân khúc RFM", hole=0.4)
fig.write_html("outputs/figures/rfm_segment_pie.html")
fig.show()

"""## 7. Phân khúc khách hàng bằng Machine Learning (KMeans Clustering)

Ngoài RFM rule-based, ta dùng **KMeans clustering** — một kỹ thuật unsupervised ML phổ biến trong DA/DS — để tự động tìm nhóm khách hàng có hành vi tương tự, khách quan hơn so với việc đặt ngưỡng thủ công.

"""

X = rfm[["Recency","Frequency","Monetary"]].copy()
X_log = np.log1p(X)  # giảm skew vì Monetary/Frequency thường lệch phải mạnh

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_log)

sil_scores = {}
for k in range(2, 8):
    km_tmp = KMeans(n_clusters=k, random_state=42, n_init=10).fit(X_scaled)
    sil_scores[k] = silhouette_score(X_scaled, km_tmp.labels_)

plt.figure(figsize=(8,4))
plt.plot(list(sil_scores.keys()), list(sil_scores.values()), marker="o")
plt.title("Silhouette Score theo số cụm k")
plt.xlabel("k"); plt.ylabel("Silhouette Score")
plt.savefig("outputs/figures/silhouette_scores.png", dpi=150)
plt.show()

best_k = max(sil_scores, key=sil_scores.get)
print(f"Số cụm tối ưu (silhouette cao nhất): k = {best_k}")

kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
rfm["Cluster"] = kmeans.fit_predict(X_scaled)

cluster_summary = rfm.groupby("Cluster")[["Recency","Frequency","Monetary"]].mean().round(1)
cluster_summary["Số khách hàng"] = rfm["Cluster"].value_counts().sort_index()
print(cluster_summary)

# Trực quan hóa cụm bằng PCA (giảm 3 chiều RFM về 2D để vẽ)
pca = PCA(n_components=2, random_state=42)
coords = pca.fit_transform(X_scaled)
rfm["PC1"], rfm["PC2"] = coords[:,0], coords[:,1]

fig = px.scatter(rfm, x="PC1", y="PC2", color=rfm["Cluster"].astype(str),
                  hover_data=["Recency","Frequency","Monetary"],
                  title=f"Phân khúc khách hàng theo KMeans (k={best_k}) - chiếu qua PCA")
fig.write_html("outputs/figures/customer_clusters.html")
fig.show()

joblib.dump(kmeans, "outputs/models/kmeans_customer_segments.pkl")
joblib.dump(scaler, "outputs/models/rfm_scaler.pkl")
rfm.to_csv("outputs/data/rfm_customer_segments.csv", index=False)
print(" Đã lưu model KMeans và bảng phân khúc khách hàng.")

"""## 8. Cohort Analysis — Đo lường khả năng giữ chân khách hàng (Retention)

Cohort Analysis nhóm khách hàng theo **tháng mua hàng đầu tiên** rồi theo dõi tỷ lệ họ còn quay lại mua ở các tháng tiếp theo. Đây là kỹ thuật rất được ưa dùng trong các công ty e-commerce/SaaS tại Việt Nam để đánh giá hiệu quả giữ chân khách hàng (retention) theo từng "lứa" khách.

"""

df["InvoiceMonth_dt"] = df["InvoiceDate"].dt.to_period("M")
df["CohortMonth"] = df.groupby("CustomerID")["InvoiceDate"].transform("min").dt.to_period("M")
df["CohortIndex"] = (df["InvoiceMonth_dt"] - df["CohortMonth"]).apply(lambda x: x.n)

cohort_data = df.groupby(["CohortMonth","CohortIndex"])["CustomerID"].nunique().reset_index()
cohort_pivot = cohort_data.pivot(index="CohortMonth", columns="CohortIndex", values="CustomerID")
cohort_size = cohort_pivot.iloc[:, 0]
retention = cohort_pivot.divide(cohort_size, axis=0)

plt.figure(figsize=(14, 7))
sns.heatmap(retention, annot=True, fmt=".0%", cmap="YlGnBu", cbar_kws={"label":"Tỷ lệ giữ chân"})
plt.title("Cohort Retention Heatmap — Tỷ lệ khách hàng quay lại theo từng tháng")
plt.xlabel("Số tháng kể từ lần mua đầu tiên")
plt.ylabel("Tháng bắt đầu (Cohort)")
plt.tight_layout()
plt.savefig("outputs/figures/cohort_retention_heatmap.png", dpi=150)
plt.show()

retention.to_csv("outputs/data/cohort_retention.csv")

"""## 9. Market Basket Analysis — Luật kết hợp sản phẩm (Association Rules)

Kỹ thuật **Apriori** tìm ra các sản phẩm thường được mua cùng nhau → nền tảng cho các tính năng "Sản phẩm thường mua cùng", gợi ý cross-sell/up-sell mà hầu hết sàn e-commerce (Tiki, Shopee, Lazada...) đều áp dụng.

>  Lưu ý: nếu bạn đang chạy trên dữ liệu mô phỏng (synthetic fallback), phần này có thể không tìm ra luật nào đáng kể vì dữ liệu được sinh ngẫu nhiên (không có "sở thích mua hàng" thật). Trên dữ liệu thật (UCI), phần này sẽ ra kết quả có ý nghĩa.

"""

# Giới hạn ở thị trường lớn nhất để bảng basket không quá thưa & tính toán nhanh hơn
top_country = df["Country"].value_counts().idxmax()
df_basket_country = df[df["Country"] == top_country]

basket = (df_basket_country.groupby(["InvoiceNo","Description"])["Quantity"]
          .sum().unstack().fillna(0))
basket_enc = basket.gt(0)  # encode boolean, tránh cảnh báo deprecation của mlxtend

frequent_itemsets = apriori(basket_enc, min_support=0.02, use_colnames=True)
print(f"Số itemset thường xuyên tìm được: {len(frequent_itemsets)}")

if len(frequent_itemsets) > 0:
    rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)
    rules = rules.sort_values("lift", ascending=False)
    display_cols = ["antecedents","consequents","support","confidence","lift"]
    print(f"\nTop 10 luật kết hợp mạnh nhất (thị trường: {top_country}):")
    print(rules[display_cols].head(10).to_string(index=False))
    rules.to_csv("outputs/data/association_rules.csv", index=False)
else:
    print("Không tìm được luật kết hợp ở mức min_support hiện tại — thử giảm min_support nếu cần.")
    rules = pd.DataFrame()

"""## 10. Dự đoán khách hàng rời bỏ (Churn Prediction)

Đây là bài toán **classification** rất phổ biến trong DA/DS tại các doanh nghiệp: dựa vào hành vi mua hàng trong "giai đoạn quan sát", dự đoán khách hàng có **còn quay lại mua ở giai đoạn sau** hay không.

Notebook chia dữ liệu theo **thời gian** (không phải random split) để tránh data leakage — đây là điểm rất hay bị làm sai trong các project churn prediction, nên mình làm đúng chuẩn ở đây để bạn tham khảo.

"""

split_date = df["InvoiceDate"].min() + (df["InvoiceDate"].max() - df["InvoiceDate"].min()) / 2
obs_period = df[df["InvoiceDate"] <= split_date]     # giai đoạn quan sát -> tính feature
future_period = df[df["InvoiceDate"] > split_date]   # giai đoạn tương lai -> xác định có quay lại không

snapshot = split_date + pd.Timedelta(days=1)
churn_feat = obs_period.groupby("CustomerID").agg(
    Recency=("InvoiceDate", lambda x: (snapshot - x.max()).days),
    Frequency=("InvoiceNo", "nunique"),
    Monetary=("Revenue", "sum"),
    AvgBasketValue=("Revenue", "mean"),
).reset_index()

returning_customers = set(future_period["CustomerID"].unique())
churn_feat["Churn"] = (~churn_feat["CustomerID"].isin(returning_customers)).astype(int)

print(f"Ngày chia mốc quan sát/tương lai: {split_date.date()}")
print(f"Tỷ lệ churn: {churn_feat['Churn'].mean():.1%}")
churn_feat.head()

feature_cols = ["Recency","Frequency","Monetary","AvgBasketValue"]
X = churn_feat[feature_cols]
y = churn_feat["Churn"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler_churn = StandardScaler()
X_train_s = scaler_churn.fit_transform(X_train)
X_test_s = scaler_churn.transform(X_test)

clf_models = {
    "Logistic Regression": LogisticRegression(max_iter=500),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": xgb.XGBClassifier(eval_metric="logloss", random_state=42, verbosity=0),
}

clf_results = []
fitted_clf = {}
for name, model in clf_models.items():
    if name == "Logistic Regression":
        model.fit(X_train_s, y_train)
        pred = model.predict(X_test_s); proba = model.predict_proba(X_test_s)[:,1]
    else:
        model.fit(X_train, y_train)
        pred = model.predict(X_test); proba = model.predict_proba(X_test)[:,1]
    fitted_clf[name] = model
    clf_results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred, zero_division=0),
        "Recall": recall_score(y_test, pred, zero_division=0),
        "F1-score": f1_score(y_test, pred, zero_division=0),
        "AUC": roc_auc_score(y_test, proba),
    })

clf_results_df = pd.DataFrame(clf_results).sort_values("F1-score", ascending=False).reset_index(drop=True)
print("=== SO SÁNH CÁC MODEL DỰ ĐOÁN CHURN ===")
clf_results_df

# ROC Curve so sánh các model
plt.figure(figsize=(8,6))
for name, model in fitted_clf.items():
    X_eval = X_test_s if name == "Logistic Regression" else X_test
    proba = model.predict_proba(X_eval)[:,1]
    fpr, tpr, _ = roc_curve(y_test, proba)
    auc = roc_auc_score(y_test, proba)
    plt.plot(fpr, tpr, label=f"{name} (AUC={auc:.2f})")

plt.plot([0,1],[0,1], "k--", alpha=0.4)
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title("ROC Curve — So sánh các model dự đoán Churn")
plt.legend()
plt.tight_layout()
plt.savefig("outputs/figures/churn_roc_curves.png", dpi=150)
plt.show()

best_model_name = clf_results_df.iloc[0]["Model"]
best_clf = fitted_clf[best_model_name]
print(f" Model tốt nhất (theo F1-score): {best_model_name}")

joblib.dump(best_clf, "outputs/models/best_churn_model.pkl")
joblib.dump(scaler_churn, "outputs/models/churn_scaler.pkl")
clf_results_df.to_csv("outputs/data/churn_model_comparison.csv", index=False)
print(" Đã lưu model churn tốt nhất và bảng so sánh.")

"""## 11. Dự đoán giá trị khách hàng (Customer Lifetime Value - CLV Proxy)

Bài toán **regression**: dự đoán tổng chi tiêu (Monetary) của khách hàng dựa trên hành vi Recency/Frequency — một dạng CLV đơn giản, giúp doanh nghiệp ưu tiên nguồn lực CSKH/marketing cho nhóm khách hàng giá trị cao.

"""

Xr = rfm[["Recency","Frequency"]]
yr = rfm["Monetary"]
Xr_train, Xr_test, yr_train, yr_test = train_test_split(Xr, yr, test_size=0.2, random_state=42)

reg_models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(n_estimators=200, random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42),
    "XGBoost": xgb.XGBRegressor(random_state=42, verbosity=0),
}

reg_results = []
fitted_reg = {}
for name, model in reg_models.items():
    model.fit(Xr_train, yr_train)
    pred = model.predict(Xr_test)
    fitted_reg[name] = model
    reg_results.append({
        "Model": name,
        "MAE": mean_absolute_error(yr_test, pred),
        "RMSE": mean_squared_error(yr_test, pred) ** 0.5,
        "R2": r2_score(yr_test, pred),
    })

reg_results_df = pd.DataFrame(reg_results).sort_values("R2", ascending=False).reset_index(drop=True)
print("=== SO SÁNH CÁC MODEL DỰ ĐOÁN GIÁ TRỊ KHÁCH HÀNG (CLV) ===")
reg_results_df

best_reg_name = reg_results_df.iloc[0]["Model"]
best_reg = fitted_reg[best_reg_name]
print(f" Model tốt nhất (theo R²): {best_reg_name}")

pred_best = best_reg.predict(Xr_test)
plt.figure(figsize=(7,6))
plt.scatter(yr_test, pred_best, alpha=0.5)
lims = [min(yr_test.min(), pred_best.min()), max(yr_test.max(), pred_best.max())]
plt.plot(lims, lims, "r--", label="Dự đoán hoàn hảo")
plt.xlabel("Monetary thực tế (£)"); plt.ylabel("Monetary dự đoán (£)")
plt.title(f"Thực tế vs Dự đoán — {best_reg_name}")
plt.legend()
plt.tight_layout()
plt.savefig("outputs/figures/clv_prediction_scatter.png", dpi=150)
plt.show()

joblib.dump(best_reg, "outputs/models/best_clv_model.pkl")
reg_results_df.to_csv("outputs/data/clv_model_comparison.csv", index=False)
print(" Đã lưu model CLV tốt nhất và bảng so sánh.")

"""## 12. Tổng hợp lưu trữ (Storage Summary)

Toàn bộ output của project được tổ chức theo chuẩn thư mục của 1 project Data Analytics thực tế:

```
outputs/
├── data/            # Dữ liệu đã xử lý, bảng RFM, kết quả model (CSV)
├── models/          # Model đã train, lưu bằng joblib (.pkl) để tái sử dụng/triển khai
└── figures/         # Biểu đồ tĩnh (.png) và tương tác (.html)
```

"""

for root, dirs, files in os.walk("outputs"):
    level = root.replace("outputs", "").count(os.sep)
    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")
    for f in files:
        size_kb = os.path.getsize(os.path.join(root, f)) / 1024
        print(f"{indent}  - {f}  ({size_kb:.1f} KB)")

"""## 13. Dashboard tương tác

Dashboard đơn giản dùng `ipywidgets` + `Plotly`, cho phép chọn quốc gia để xem doanh thu, top sản phẩm và phân khúc khách hàng tương ứng — mô phỏng 1 dashboard nội bộ dạng "self-service BI" mà nhiều doanh nghiệp Việt Nam xây cho các phòng kinh doanh tự khám phá dữ liệu.

"""

country_options = ["Tất cả"] + sorted(df["Country"].unique().tolist())
country_dropdown = widgets.Dropdown(options=country_options, value="Tất cả", description="Quốc gia:")
output_area = widgets.Output()

def update_dashboard(change=None):
    with output_area:
        output_area.clear_output(wait=True)
        selected = country_dropdown.value
        d = df if selected == "Tất cả" else df[df["Country"] == selected]

        if len(d) == 0:
            print("Không có dữ liệu cho lựa chọn này.")
            return

        fig = make_subplots(rows=1, cols=2, subplot_titles=("Doanh thu theo tháng", "Top 5 sản phẩm"))

        monthly = d.groupby(d["InvoiceDate"].dt.to_period("M").astype(str))["Revenue"].sum().reset_index()
        monthly.columns = ["Month", "Revenue"]
        fig.add_trace(go.Scatter(x=monthly["Month"], y=monthly["Revenue"], mode="lines+markers"), row=1, col=1)

        top5 = d.groupby("Description")["Revenue"].sum().sort_values(ascending=False).head(5)
        fig.add_trace(go.Bar(x=top5.values, y=top5.index, orientation="h"), row=1, col=2)

        fig.update_layout(height=420, width=950, showlegend=False,
                           title_text=f"Dashboard — {selected} | Tổng doanh thu: £{d['Revenue'].sum():,.0f} | Số KH: {d['CustomerID'].nunique():,}")
        fig.show()

country_dropdown.observe(update_dashboard, names="value")
display(country_dropdown, output_area)
update_dashboard()

"""## 14. Tổng kết & Insight kinh doanh

**Các kỹ thuật DA/DS phổ biến đã áp dụng trong notebook này** — cũng là các kỹ thuật mà nhiều doanh nghiệp bán lẻ/e-commerce tại Việt Nam (Tiki, Thế Giới Di Động, Sendo, các chuỗi F&B/retail...) thường yêu cầu ở vị trí Data Analyst/Data Scientist:

1. **RFM Analysis** – phân loại khách hàng theo giá trị, dùng cho email marketing/CSKH có mục tiêu.
2. **Customer Segmentation (KMeans)** – nhóm khách hàng tự động dựa trên hành vi, hỗ trợ chiến lược cá nhân hoá.
3. **Cohort Analysis** – theo dõi retention theo từng lứa khách hàng, đánh giá hiệu quả giữ chân.
4. **Market Basket Analysis** – gợi ý sản phẩm liên quan, tăng AOV (Average Order Value).
5. **Churn Prediction** – dự đoán sớm khách hàng có nguy cơ rời bỏ để can thiệp kịp thời (voucher, remarketing...).
6. **CLV Prediction** – ưu tiên nguồn lực cho nhóm khách hàng giá trị cao.

**Gợi ý mở rộng project:**
- Thêm dữ liệu marketing (chi phí quảng cáo, kênh) để tính CAC, ROAS.
- Dùng time series (Prophet/ARIMA) để forecast doanh thu dài hạn.
- Triển khai model churn dưới dạng API (FastAPI/Flask) để tích hợp CRM thật.
- A/B testing cho các chiến dịch retention dựa trên phân khúc RFM.

---
*Notebook được xây dựng phục vụ mục đích học tập/portfolio Data Analytics. Dataset: UCI Online Retail Dataset (Chen, D., 2015).*

"""